development:
  secret_key_base: development_secret_key_base_not_used_in_production

test:
  secret_key_base: test_secret_key_base_not_used_in_production

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { "22232afe6df956bedfdc6614c0817e1402fac73cd5820ab60679e97122ebfa6ef078f51bbb02819abf15701a0b9579a712cee37c8bc409f2ba3fd81ca4bbd07d" } %>
